site_name: Desenvolupament d'interfícies 21-22
site_url: https://fpieseljust.github.io/di21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitats:
      - Unitat 2 - Introducció a PySide6:
        - Introducció: unitats/pyside6/pyside6-intro.md
        - Signals - Slots: unitats/pyside6/pyside6-signals-slots.md
        - Widgets: unitats/pyside6/pyside6-widgets.md
        - Layouts: unitats/pyside6/pyside6-layouts.md
        - Pràctica 2: unitats/pyside6/pyside6-practica-calculadora.md
    - About: about.md
theme:
  name: material