site_name: Desenvolupament d'interfícies 21-22
site_url: https://fpieseljust.github.io/di21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitats:
      - Unitat 2 - Introducció a PySide6:
        - Introducció: unitats/pyside6/teoria/pyside6-intro.md
        - Signals - Slots: unitats/pyside6/teoria/pyside6-signals-slots.md
        - Widgets: unitats/pyside6/teoria/pyside6-widgets.md
        - Layouts: unitats/pyside6/teoria/pyside6-layouts.md
        - Menús, barres de ferramentes i barres d'estat: unitats/pyside6/teoria/pyside6-menu-actions.md
        - Dialegs i alertes: unitats/pyside6/teoria/pyside6-dialogs-alerts.md
        - Finestres: unitats/pyside6/teoria/windows.md
    - Pràctiques i treballs:
      - PySide6:
        - Pràctica calculadora: unitats/pyside6/practiques/pyside6-practica-calculadora.md
        - Pràctica login: unitats/pyside6/practiques/login.md
    - About: about.md
theme:
  name: material
  features:
    - content.code.annotate
    - search.suggest
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences